- name: check installed extensions
  shell: code --list-extensions
  check_mode: False
  changed_when: False
  ignore_errors: True
  register: code_exts

- name: install extensions
  shell: "code --install-extension {{ item }}"
  with_items: "{{ extensions }}"
  when:  item not in code_exts.stdout

- name: test
  shell: " ls -l {{ item }}"
  with_items:
    - ~/Library/
    - ~/Library/ApplicationSupport/
    - ~/Library/ApplicationSupport/Code/
    - ~/Library/ApplicationSupport/Code/User/
    - ~/Library/Application\ Support/Code/User/
    - ~/Library/Application\ Support/Code/
    - ~/Library/Application\ Support/
    - ~/Library/Application\ Support/Code/User/
  changed_when: False

- name: set key mapping
  copy:
    src: keybindings.json
    dest: ~/Library/ApplicationSupport/Code/User/keybindings.json

