- name: test
  shell: "ls -l {{ item }}"
  with_items:
    - /Applications/
    - /Applications/Docker.app/
    - /Applications/Docker.app/Contents/
    - /Applications/Docker.app/Contents/Resources/
    - /Applications/Docker.app/Contents/Resources/etc/
  changed_when: False

- name: enable zsh completion for docker
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/{{ item }}.zsh-completion"
    dest: "/usr/local/share/zsh/site-functions/_{{ item }}"
    state: link
  with_items:
    - docker
    - docker-compose
    - docker-machine
