- name: enable zsh as login shell
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/zsh'

- name: set zsh as login shell
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/local/bin/zsh

- name: set completion for ccat
  get_url:
    url: https://raw.githubusercontent.com/jingweno/ccat/master/completion/zsh/_ccat
    dest: /usr/local/share/zsh/site-functions/_ccat
