extensions:
  - CoenraadS.bracket-pair-colorizer-2
  - ms-python.python
  - shardulm94.trailing-spaces
  #- vscode-icons-team.vscode-icons
  - vscoss.vscode-ansible
  #- yzhang.markdown-all-in-one
  #- oderwat.indent-rainbow
  - ms-azuretools.vscode-docker
  #- vscodevim.vim
  - redhat.vscode-yaml
  - mechatroner.rainbow-csv
  - ms-vscode.wordcount
  - ms-vscode-remote.vscode-remote-extensionpack
  #- streetsidesoftware.code-spell-checker
  #- streetsidesoftware.code-spell-checker-german
  - wholroyd.jinja
  
